Fix cancellation in ReceiveFrameBytesAsync
zeromq/netmq pull request #966
Opened 2021-02-11 11:55 UTC by jkarder

This PR updates ReceiveFrameBytesAsync to detach competing listeners before finishing the TaskCompletionSource and calls `TrySetResult` and `TrySetCanceled` instead of `SetResult` and `SetCanceled`.

Fixes #965.

2021-02-11 12:43 UTC, drewnoakes commented
The same treatment is needed in `ReceiveFrameStringAsync`. I don't know why `SkipFrameAsync` doesn't support cancellation, but you could add it there too as the pattern is similar.

Also, it's worth checking `token.CanBeCanceled`, as `default(CancellationToken)` will never be cancelled and so there's no point registering. For many users, no cancellation will be required, so we can avoid the callback registration overhead completely.

2021-02-11 22:23 UTC, drewnoakes approved these changes

2021-02-11 22:25 UTC, drewnoakes requested changes
Just noticed the test failures. Please fix those up and we'll get this merged.

@somdoron does this look good to you? There is an API change here.

2021-02-11 23:34 UTC, somdoron approved these changes

2021-02-11 23:35 UTC, somdoron commented
LGTM

2021-02-12 08:34 UTC, abeham commented
The tests succeed locally on my Windows 10 installation for netcoreapp2.1, netcoreapp3.1, and net47. Maybe the build server had some hickups, because the failing test is a timeout.

2021-02-12 09:14 UTC, jkarder commented
Thanks for your approvals. The tests succeed here as well (Windows 10.0.19041).

netcoreapp2.1:
```
Test Run Successful.
Total tests: 256
     Passed: 240
    Skipped: 16
 Total time: 37.3524 Seconds
```

netcoreapp3.1:
```
Test Run Successful.
Total tests: 258
     Passed: 242
    Skipped: 16
 Total time: 38.2665 Seconds
```

net47:
```
Test Run Successful.
Total tests: 259
     Passed: 243
    Skipped: 16
 Total time: 39.0455 Seconds
```

BTW, would you like me to revert the whitespace changes I accidentally committed in d297a27?

2021-02-15 01:24 UTC, drewnoakes commented
Re-running jobs to see if that helps.

> BTW, would you like me to revert the whitespace changes I accidentally committed in d297a27?

Sure, but only if it's convenient.

2021-02-15 01:46 UTC, drewnoakes commented
Yep, just needed a kick. I'll merge as-is. Thanks very much!

2021-02-15 01:46 UTC, merged